### ISSUE TITLE
No title

### ISSUE THREAD

**Issue by marksteward** [marksteward/earlbot#19]
for http://tylervigen.com

**Comment by firesock** [comment]
Site seems to be doing something weird with user agents; No user agent, or one stolen from my browser works, but something like 'Mozilla/5.0' causes a 406, what's on the server's earl.conf?

**Comment by firesock** [comment]
Same with this http://trixter.oldskool.org/2014/06/19/8088-domination-post-mortem-part-1/

**Comment by marksteward** [comment]
Ooh interesting:

```
Mark@london:~$ curl -i 'http://tylervigen.com/'
HTTP/1.1 302 Moved Temporarily
Date: Sun, 31 May 2015 17:56:27 GMT
Server: Apache
location: spurious-correlations
Vary: Accept-Encoding
Content-Length: 0
Connection: close
Content-Type: text/html
```
